"""CHW Navigator package."""

from .bundles import BundleArtifacts, BundleBuildError, create_bundle
from .catalogs import CatalogBundle, CatalogLoadError, compose_document_from_catalogs, load_catalog_bundle
from .change_control import ChangeReviewArtifacts, ChangeReviewBuildError, create_change_review_package, load_change_memo
from .clinical_ir import ClinicalIRDocument
from .compare import (
    ComparisonCase,
    ComparisonError,
    MismatchEntry,
    PairwiseCaseResult,
    build_comparison_log,
    build_z3_checks_log,
    compare_backends,
    compare_document_pair,
    compare_workbook_pair,
    load_patient_cases,
)
from .evaluator import EvaluationError, EvaluationResult, evaluate_document
from .form_ir import load_xlsform_workbook
from .headless_runner import HeadlessEvaluationResult, HeadlessRunnerError, evaluate_workbook_headless
from .json_schema_export import build_json_schema, write_json_schemas
from .mermaid_backend import (
    MermaidArtifact,
    MermaidComparisonResult,
    build_mermaid,
    build_mermaid_artifact,
    compare_mermaid_text,
)
from .staged_lint import (
    StageLintIssue,
    StageLintReport,
    lint_ir_document,
    lint_mermaid_artifact,
    lint_smt_artifact,
    lint_xlsform_artifacts,
    preflight_source_artifact,
    render_stage_lint_report,
)
from .validator import ValidationError, validate_document
from .xlsform_import import (
    ImportedXLSForm,
    XLSFormImportError,
    XLSFormImportFinding,
    XLSFormImportReport,
    import_xlsform_files,
    import_xlsform_files_detailed,
    import_xlsform_workbook,
)
from .z3_backend import (
    SmtLibComparisonResult,
    Z3AnalysisReport,
    Z3CheckResult,
    Z3GeneratedCase,
    Z3Witness,
    analyze_document,
    compare_smt2_file,
    compare_smt2_text,
    evaluate_patient,
    evaluate_smt2_file,
    evaluate_smt2_text,
    export_smt2,
    generate_test_patients,
    write_smt2,
)

__all__ = [
    "BundleArtifacts",
    "BundleBuildError",
    "CatalogBundle",
    "CatalogLoadError",
    "ChangeReviewArtifacts",
    "ChangeReviewBuildError",
    "ClinicalIRDocument",
    "ComparisonCase",
    "ComparisonError",
    "EvaluationError",
    "EvaluationResult",
    "HeadlessEvaluationResult",
    "HeadlessRunnerError",
    "ImportedXLSForm",
    "build_json_schema",
    "XLSFormImportFinding",
    "XLSFormImportReport",
    "MermaidArtifact",
    "MermaidComparisonResult",
    "MismatchEntry",
    "PairwiseCaseResult",
    "SmtLibComparisonResult",
    "StageLintIssue",
    "StageLintReport",
    "Z3AnalysisReport",
    "Z3CheckResult",
    "Z3GeneratedCase",
    "Z3Witness",
    "ValidationError",
    "analyze_document",
    "build_mermaid",
    "build_mermaid_artifact",
    "build_comparison_log",
    "build_z3_checks_log",
    "compare_backends",
    "compare_document_pair",
    "compare_mermaid_text",
    "compare_smt2_file",
    "compare_smt2_text",
    "compare_workbook_pair",
    "compose_document_from_catalogs",
    "create_change_review_package",
    "create_bundle",
    "evaluate_document",
    "evaluate_workbook_headless",
    "evaluate_patient",
    "evaluate_smt2_file",
    "evaluate_smt2_text",
    "export_smt2",
    "generate_test_patients",
    "import_xlsform_files",
    "import_xlsform_files_detailed",
    "import_xlsform_workbook",
    "lint_ir_document",
    "lint_mermaid_artifact",
    "lint_smt_artifact",
    "lint_xlsform_artifacts",
    "load_catalog_bundle",
    "load_change_memo",
    "load_xlsform_workbook",
    "load_patient_cases",
    "preflight_source_artifact",
    "render_stage_lint_report",
    "validate_document",
    "write_json_schemas",
    "write_smt2",
    "XLSFormImportError",
]
