"""CHW Navigator package."""

from .bundles import BundleArtifacts, BundleBuildError, create_bundle
from .catalogs import CatalogBundle, CatalogLoadError, compose_document_from_catalogs, load_catalog_bundle
from .change_control import ChangeReviewArtifacts, ChangeReviewBuildError, create_change_review_package, load_change_memo
from .clinical_ir import ClinicalIRDocument
from .cht_special_functions import (
    CHTSpecialFunctionBundle,
    ReviewedCHTProfile,
    lower_reviewed_special_functions,
    reviewed_cht_profile,
    reviewed_cht_versions,
    write_cht_special_function_bundle,
)
from .cht_backend import build_cht_lowering_plan, write_cht_adapter_bundle
from .cht_tasks import (
    CHT_TASK_BINDING_SCHEMA_VERSION,
    CHTTaskBindingRegistry,
    CHTTaskIntentPlan,
    CHTTaskLoweringError,
    CHTTaskTypeBinding,
    generate_tasks_js,
    load_cht_task_bindings,
    parse_cht_task_bindings,
)
from .clinical_vocabulary import (
    CLINICAL_VOCABULARY_VERSION,
    clinical_object_findings,
    contains_clinical_derivation,
    reject_clinical_derivation,
)
from .compare import (
    ComparisonCase,
    ComparisonError,
    MismatchEntry,
    PairwiseCaseResult,
    build_comparison_log,
    build_z3_checks_log,
    compare_backends,
    compare_document_pair,
    compare_workbook_pair,
    derive_comparison_cases,
    load_patient_cases,
)
from .evaluator import EvaluationError, EvaluationResult, evaluate_document
from .equivalence import EquivalenceArtifacts, build_case_suite_equivalence_report
from .form_ir import load_xlsform_workbook
from .headless_runner import HeadlessEvaluationResult, HeadlessRunnerError, evaluate_workbook_headless
from .json_schema_export import build_json_schema, write_json_schemas
from .mermaid_backend import (
    MermaidArtifact,
    MermaidComparisonResult,
    build_mermaid,
    build_mermaid_artifact,
    compare_mermaid_text,
)
from .mutable_conflicts import (
    CHTConflictFixture,
    ConflictPolicyRegistry,
    CorrectionEvent,
    FHIRVersionConflictFixture,
    MutableConflictResolution,
    correction_events_from_cht_conflict_fixture,
    resolve_mutable_field_conflicts,
    review_obligation_from_fhir_conflict_fixture,
    validate_conflict_policy_registry,
)
from .person_identity import (
    CREATE_PERSON_IDENTITY_SERVICE,
    ConfirmNewProvenance,
    IdentityPersonRecord,
    IdentityProviderConfig,
    IdentityQuery,
    PersonIdentityResolutionRequest,
    PersonIdentityResolutionResult,
    deterministic_identity_candidates,
    resolve_person_identity,
    validate_identity_provider,
)
from .quality_checks import QualityCheckArtifacts, run_quality_checks
from .staged_lint import (
    StageLintIssue,
    StageLintReport,
    lint_ir_document,
    lint_mermaid_artifact,
    lint_smt_artifact,
    lint_xlsform_artifacts,
    preflight_source_artifact,
    render_stage_lint_report,
)
from .special_functions import (
    SPECIAL_FUNCTION_STATUSES,
    SpecialFunctionResult,
    calculate_gestational_age_from_lmp,
)
from .validator import ValidationError, validate_document
from .xlsform_import import (
    ImportedXLSForm,
    XLSFormImportError,
    XLSFormImportFinding,
    XLSFormImportReport,
    import_xlsform_files,
    import_xlsform_files_detailed,
    import_xlsform_workbook,
)
from .xlsform_proof import XLSFormProofArtifacts, build_xlsform_roundtrip_proof
from .z3_backend import (
    SmtLibComparisonResult,
    Z3AnalysisReport,
    Z3CheckResult,
    Z3GeneratedCase,
    Z3Witness,
    analyze_document,
    compare_smt2_file,
    compare_smt2_text,
    evaluate_patient,
    evaluate_smt2_file,
    evaluate_smt2_text,
    export_smt2,
    generate_test_patients,
    write_smt2,
)

__all__ = [
    "BundleArtifacts",
    "BundleBuildError",
    "CatalogBundle",
    "CatalogLoadError",
    "CHTConflictFixture",
    "ChangeReviewArtifacts",
    "ChangeReviewBuildError",
    "ClinicalIRDocument",
    "ConflictPolicyRegistry",
    "ConfirmNewProvenance",
    "CorrectionEvent",
    "CREATE_PERSON_IDENTITY_SERVICE",
    "CHTSpecialFunctionBundle",
    "CHT_TASK_BINDING_SCHEMA_VERSION",
    "CHTTaskBindingRegistry",
    "CHTTaskIntentPlan",
    "CHTTaskLoweringError",
    "CHTTaskTypeBinding",
    "CLINICAL_VOCABULARY_VERSION",
    "ComparisonCase",
    "ComparisonError",
    "EquivalenceArtifacts",
    "EvaluationError",
    "EvaluationResult",
    "FHIRVersionConflictFixture",
    "HeadlessEvaluationResult",
    "HeadlessRunnerError",
    "ImportedXLSForm",
    "IdentityPersonRecord",
    "IdentityProviderConfig",
    "IdentityQuery",
    "XLSFormProofArtifacts",
    "build_json_schema",
    "XLSFormImportFinding",
    "XLSFormImportReport",
    "MermaidArtifact",
    "MermaidComparisonResult",
    "MismatchEntry",
    "MutableConflictResolution",
    "PairwiseCaseResult",
    "PersonIdentityResolutionRequest",
    "PersonIdentityResolutionResult",
    "QualityCheckArtifacts",
    "ReviewedCHTProfile",
    "SmtLibComparisonResult",
    "StageLintIssue",
    "StageLintReport",
    "SPECIAL_FUNCTION_STATUSES",
    "SpecialFunctionResult",
    "Z3AnalysisReport",
    "Z3CheckResult",
    "Z3GeneratedCase",
    "Z3Witness",
    "ValidationError",
    "analyze_document",
    "build_mermaid",
    "build_cht_lowering_plan",
    "build_mermaid_artifact",
    "build_comparison_log",
    "build_case_suite_equivalence_report",
    "build_z3_checks_log",
    "calculate_gestational_age_from_lmp",
    "clinical_object_findings",
    "compare_backends",
    "compare_document_pair",
    "compare_mermaid_text",
    "compare_smt2_file",
    "compare_smt2_text",
    "compare_workbook_pair",
    "contains_clinical_derivation",
    "compose_document_from_catalogs",
    "correction_events_from_cht_conflict_fixture",
    "run_quality_checks",
    "create_change_review_package",
    "create_bundle",
    "derive_comparison_cases",
    "deterministic_identity_candidates",
    "evaluate_document",
    "evaluate_workbook_headless",
    "evaluate_patient",
    "evaluate_smt2_file",
    "evaluate_smt2_text",
    "export_smt2",
    "generate_test_patients",
    "generate_tasks_js",
    "import_xlsform_files",
    "import_xlsform_files_detailed",
    "import_xlsform_workbook",
    "build_xlsform_roundtrip_proof",
    "lint_ir_document",
    "lint_mermaid_artifact",
    "lint_smt_artifact",
    "lint_xlsform_artifacts",
    "lower_reviewed_special_functions",
    "load_catalog_bundle",
    "load_cht_task_bindings",
    "load_change_memo",
    "load_xlsform_workbook",
    "load_patient_cases",
    "preflight_source_artifact",
    "parse_cht_task_bindings",
    "render_stage_lint_report",
    "reject_clinical_derivation",
    "resolve_mutable_field_conflicts",
    "resolve_person_identity",
    "review_obligation_from_fhir_conflict_fixture",
    "reviewed_cht_profile",
    "reviewed_cht_versions",
    "validate_document",
    "validate_conflict_policy_registry",
    "validate_identity_provider",
    "write_json_schemas",
    "write_cht_special_function_bundle",
    "write_cht_adapter_bundle",
    "write_smt2",
    "XLSFormImportError",
]
