from __future__ import annotations

from dataclasses import dataclass
from enum import StrEnum


class DiagnosticCode(StrEnum):
    CLINICAL_DERIVATION_FORBIDDEN = "CHT-SAFETY-003"
    UNREVIEWED_CHT_VERSION = "CHT-VERSION-002"
    NATIVE_REFERENCE_DATA_UNVERIFIED = "CHT-SPECIAL-001"
    INVALID_EXTENSION_RETURN = "CHT-SPECIAL-002"
    CHT_TASK_BINDING_INVALID = "CHT-TASK-001"
    CHT_TASK_TYPE_UNBOUND = "CHT-TASK-002"
    CHT_TASK_SCHEDULE_UNSUPPORTED = "CHT-TASK-003"
    CHT_TASK_IDENTITY_COLLISION = "CHT-TASK-004"
    STATUS_COVERAGE_INCOMPLETE = "PSR-INV-008"
    IMPLEMENTATION_DIGEST_MISMATCH = "PSR-INV-009"
    VECTOR_DIGEST_MISMATCH = "PSR-INV-010"
    IDENTITY_PROVIDER_MISSING = "PSR-ID-001"
    IDENTITY_DISCLOSURE_INVALID = "PSR-ID-002"
    IDENTITY_PROVENANCE_MISSING = "PSR-ID-003"
    IDENTITY_MERGE_FORBIDDEN = "PSR-ID-004"
    IDENTITY_OFFLINE_SCOPE_MISSING = "PSR-ID-005"
    CONFLICT_POLICY_MISSING = "PSR-CONFLICT-001"
    CONFLICT_RESOLVER_INVALID = "PSR-CONFLICT-002"
    CONFLICT_ASSERTION_DROPPED = "PSR-CONFLICT-003"
    CONFLICT_DEVICE_TIME_AUTHORITY = "PSR-CONFLICT-004"
    CONFLICT_CLINICAL_EVIDENCE_MUTABLE = "PSR-CONFLICT-005"


@dataclass(frozen=True, slots=True)
class Diagnostic:
    code: DiagnosticCode
    severity: str
    message: str
    path: str | None = None
