from __future__ import annotations

from dataclasses import dataclass
from enum import StrEnum


class DiagnosticCode(StrEnum):
    REGISTRY_SCHEMA_INVALID = "CHWN-REG-000"
    REGISTRY_UNIT_MISSING = "CHWN-REG-001"
    REGISTRY_VERSION_MISSING = "CHWN-REG-002"
    REGISTRY_DIGEST_MISSING = "CHWN-REG-003"
    REGISTRY_DIGEST_MISMATCH = "CHWN-REG-004"
    REGISTRY_CANDIDATE_UNRESOLVED = "CHWN-REG-005"
    REGISTRY_UNKNOWN_FIELD = "CHWN-REG-006"
    REGISTRY_RELEASE_REQUIRES_V2 = "CHWN-REG-007"
    REGISTRY_APPROVAL_DIGEST_MISMATCH = "CHWN-REG-008"
    REGISTRY_APPROVAL_ROLE_MISSING = "CHWN-REG-009"
    REGISTRY_APPROVAL_ROLE_DUPLICATE = "CHWN-REG-010"
    REGISTRY_APPROVAL_UNVERIFIED = "CHWN-REG-011"
    REGISTRY_APPROVAL_REJECTED = "CHWN-REG-012"
    REGISTRY_INPUT_INACTIVE = "CHWN-REG-013"
    REGISTRY_APPROVAL_EXPIRED = "CHWN-REG-014"
    REGISTRY_CONCEPT_BINDING_INVALID = "CHWN-REG-015"
    CAPABILITY_REFERENCE_UNRESOLVED = "CHWN-RESOLVE-001"
    CAPABILITY_INVOCATION_INVALID = "CHWN-RESOLVE-002"
    CAPABILITY_NEED_UNRESOLVED = "CHWN-RESOLVE-003"
    CAPABILITY_NEED_AMBIGUOUS = "CHWN-RESOLVE-004"
    CAPABILITY_NEED_CONTRACT_MISMATCH = "CHWN-RESOLVE-005"
    REGISTRY_RELEASE_MISMATCH = "CHWN-RESOLVE-006"
    PRODUCT_CONTRACT_INVALID = "CHWN-BRIDGE-001"
    PRODUCT_FIELD_UNSUPPORTED = "CHWN-BRIDGE-002"
    PRODUCT_PROVENANCE_LOSS = "CHWN-BRIDGE-003"
    TARGET_PROFILE_UNSUPPORTED = "CHWN-TARGET-001"
    TARGET_FEATURE_MISSING = "CHWN-TARGET-002"
    SUBJECT_SCOPE_GROUP_UNSUPPORTED = "CHWN-SCOPE-001"
    SUBJECT_SCOPE_MISSING = "CHWN-SCOPE-002"
    CLINICAL_DERIVATION_FORBIDDEN = "CHT-SAFETY-003"
    UNREVIEWED_CHT_VERSION = "CHT-VERSION-002"
    NATIVE_REFERENCE_DATA_UNVERIFIED = "CHT-SPECIAL-001"
    INVALID_EXTENSION_RETURN = "CHT-SPECIAL-002"
    CHT_TASK_BINDING_INVALID = "CHT-TASK-001"
    CHT_TASK_TYPE_UNBOUND = "CHT-TASK-002"
    CHT_TASK_SCHEDULE_UNSUPPORTED = "CHT-TASK-003"
    CHT_TASK_IDENTITY_COLLISION = "CHT-TASK-004"
    CHT_CAPABILITY_LOWERER_UNBOUND = "CHT-CAP-001"
    CHT_RUNTIME_BINDING_INVALID = "CHT-RUNTIME-001"
    CHT_COMPOSITION_INVALID = "CHT-COMPOSE-001"
    CHT_LOCAL_DATA_REGISTRY_INVALID = "CHT-LOCAL-001"
    CHT_LOCAL_DATA_BINDING_UNBOUND = "CHT-LOCAL-002"
    CHT_LOCAL_DATA_CONTEXT_UNAVAILABLE = "CHT-LOCAL-003"
    CHT_LOCAL_DATA_TYPE_MISMATCH = "CHT-LOCAL-004"
    TOPOLOGY_SNAPSHOT_INVALID = "CHWN-TOPO-001"
    TOPOLOGY_STALE = "CHWN-TOPO-002"
    TOPOLOGY_RESOLUTION_BLOCKED = "CHWN-TOPO-003"
    QUEUE_CONTRACT_INVALID = "CHWN-QUEUE-001"
    EVIDENCE_RUNNER_INVALID = "CHWN-EVIDENCE-001"
    STATUS_COVERAGE_INCOMPLETE = "PSR-INV-008"
    IMPLEMENTATION_DIGEST_MISMATCH = "PSR-INV-009"
    VECTOR_DIGEST_MISMATCH = "PSR-INV-010"
    IDENTITY_PROVIDER_MISSING = "PSR-ID-001"
    IDENTITY_DISCLOSURE_INVALID = "PSR-ID-002"
    IDENTITY_PROVENANCE_MISSING = "PSR-ID-003"
    IDENTITY_MERGE_FORBIDDEN = "PSR-ID-004"
    IDENTITY_OFFLINE_SCOPE_MISSING = "PSR-ID-005"
    CONFLICT_POLICY_MISSING = "PSR-CONFLICT-001"
    CONFLICT_RESOLVER_INVALID = "PSR-CONFLICT-002"
    CONFLICT_ASSERTION_DROPPED = "PSR-CONFLICT-003"
    CONFLICT_DEVICE_TIME_AUTHORITY = "PSR-CONFLICT-004"
    CONFLICT_CLINICAL_EVIDENCE_MUTABLE = "PSR-CONFLICT-005"


@dataclass(frozen=True, slots=True)
class Diagnostic:
    code: DiagnosticCode
    severity: str
    message: str
    path: str | None = None
