from __future__ import annotations

import json
import platform
import re
import shutil
import sys
from dataclasses import dataclass
from datetime import datetime
from pathlib import Path
from typing import Iterable


ROOT = Path(__file__).resolve().parents[1]
GENERATED = ROOT / "generated"
TEST_RUNS = GENERATED / "t"


@dataclass(slots=True)
class TestRunPaths:
    run_dir: Path
    inputs_dir: Path
    outputs_dir: Path
    scratch_dir: Path
    metadata_path: Path
    readme_path: Path


def create_test_run(
    *,
    suite_name: str,
    test_name: str,
    purpose: str,
    input_paths: Iterable[Path | str] = (),
) -> TestRunPaths:
    suite_slug = _slugify(suite_name)[:12]
    test_slug = _slugify(test_name)[:16]
    timestamp = datetime.now().strftime("%Y%m%d-%H%M%S")
    run_dir = TEST_RUNS / suite_slug / f"{timestamp}-{test_slug}"
    counter = 2
    while run_dir.exists():
        run_dir = TEST_RUNS / suite_slug / f"{timestamp}-{test_slug}-{counter:02d}"
        counter += 1

    inputs_dir = run_dir / "inputs"
    outputs_dir = run_dir / "outputs"
    scratch_dir = run_dir / "scratch"
    for path in (inputs_dir, outputs_dir, scratch_dir):
        path.mkdir(parents=True, exist_ok=True)

    normalized_inputs = [str(Path(item).resolve()) for item in input_paths]
    metadata = {
        "created_at": datetime.now().isoformat(timespec="seconds"),
        "suite_name": suite_name,
        "test_name": test_name,
        "purpose": purpose,
        "python": sys.version.split()[0],
        "platform": platform.platform(),
        "input_paths": normalized_inputs,
        "layout": {
            "inputs": "inputs/",
            "outputs": "outputs/",
            "scratch": "scratch/",
        },
    }
    metadata_path = run_dir / "metadata.json"
    metadata_path.write_text(json.dumps(metadata, indent=2, sort_keys=True) + "\n", encoding="utf-8")

    readme_lines = [
        f"# Test Run `{run_dir.name}`",
        "",
        f"- Suite: `{suite_name}`",
        f"- Test: `{test_name}`",
        f"- Created: `{metadata['created_at']}`",
        f"- Python: `{metadata['python']}`",
        f"- Platform: `{metadata['platform']}`",
        "",
        "## Purpose",
        "",
        purpose,
        "",
        "## Inputs",
        "",
    ]
    if normalized_inputs:
        readme_lines.extend(f"- `{item}`" for item in normalized_inputs)
    else:
        readme_lines.append("- none")
    readme_lines.extend(
        [
            "",
            "## Output Layout",
            "",
            "- `inputs/` copied or synthesized inputs for this test run",
            "- `outputs/` artifacts generated by the code under test",
            "- `scratch/` temporary intermediate files that support the test",
            "",
        ]
    )
    readme_path = run_dir / "README.md"
    readme_path.write_text("\n".join(readme_lines), encoding="utf-8")

    return TestRunPaths(
        run_dir=run_dir,
        inputs_dir=inputs_dir,
        outputs_dir=outputs_dir,
        scratch_dir=scratch_dir,
        metadata_path=metadata_path,
        readme_path=readme_path,
    )


def reset_suite_runs(suite_name: str) -> Path:
    suite_dir = TEST_RUNS / _slugify(suite_name)
    if suite_dir.exists():
        shutil.rmtree(suite_dir)
    suite_dir.mkdir(parents=True, exist_ok=True)
    return suite_dir


def _slugify(value: str) -> str:
    slug = re.sub(r"[^a-z0-9]+", "-", value.lower())
    return slug.strip("-") or "run"
